inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 80

Metrics/BlockLength:
  Max: 500

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 100
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 8
